// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/pb/beers.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_OK  Status = 0
	Status_BAD Status = 1
)

var Status_name = map[int32]string{
	0: "OK",
	1: "BAD",
}

var Status_value = map[string]int32{
	"OK":  0,
	"BAD": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_75daee14f32918a9, []int{0}
}

type BeerAddResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	ErrMsg               string   `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeerAddResponse) Reset()         { *m = BeerAddResponse{} }
func (m *BeerAddResponse) String() string { return proto.CompactTextString(m) }
func (*BeerAddResponse) ProtoMessage()    {}
func (*BeerAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75daee14f32918a9, []int{0}
}

func (m *BeerAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeerAddResponse.Unmarshal(m, b)
}
func (m *BeerAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeerAddResponse.Marshal(b, m, deterministic)
}
func (m *BeerAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeerAddResponse.Merge(m, src)
}
func (m *BeerAddResponse) XXX_Size() int {
	return xxx_messageInfo_BeerAddResponse.Size(m)
}
func (m *BeerAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeerAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeerAddResponse proto.InternalMessageInfo

func (m *BeerAddResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BeerAddResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BeerAddResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *BeerAddResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type BeerAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeerAddRequest) Reset()         { *m = BeerAddRequest{} }
func (m *BeerAddRequest) String() string { return proto.CompactTextString(m) }
func (*BeerAddRequest) ProtoMessage()    {}
func (*BeerAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75daee14f32918a9, []int{1}
}

func (m *BeerAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeerAddRequest.Unmarshal(m, b)
}
func (m *BeerAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeerAddRequest.Marshal(b, m, deterministic)
}
func (m *BeerAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeerAddRequest.Merge(m, src)
}
func (m *BeerAddRequest) XXX_Size() int {
	return xxx_messageInfo_BeerAddRequest.Size(m)
}
func (m *BeerAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeerAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeerAddRequest proto.InternalMessageInfo

func (m *BeerAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BeerRemoveResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	ErrMsg               string   `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeerRemoveResponse) Reset()         { *m = BeerRemoveResponse{} }
func (m *BeerRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*BeerRemoveResponse) ProtoMessage()    {}
func (*BeerRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75daee14f32918a9, []int{2}
}

func (m *BeerRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeerRemoveResponse.Unmarshal(m, b)
}
func (m *BeerRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeerRemoveResponse.Marshal(b, m, deterministic)
}
func (m *BeerRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeerRemoveResponse.Merge(m, src)
}
func (m *BeerRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_BeerRemoveResponse.Size(m)
}
func (m *BeerRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeerRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeerRemoveResponse proto.InternalMessageInfo

func (m *BeerRemoveResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BeerRemoveResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BeerRemoveResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *BeerRemoveResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type BeerRemoveRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeerRemoveRequest) Reset()         { *m = BeerRemoveRequest{} }
func (m *BeerRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*BeerRemoveRequest) ProtoMessage()    {}
func (*BeerRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75daee14f32918a9, []int{3}
}

func (m *BeerRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeerRemoveRequest.Unmarshal(m, b)
}
func (m *BeerRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeerRemoveRequest.Marshal(b, m, deterministic)
}
func (m *BeerRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeerRemoveRequest.Merge(m, src)
}
func (m *BeerRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_BeerRemoveRequest.Size(m)
}
func (m *BeerRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeerRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeerRemoveRequest proto.InternalMessageInfo

func (m *BeerRemoveRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Status", Status_name, Status_value)
	proto.RegisterType((*BeerAddResponse)(nil), "pb.BeerAddResponse")
	proto.RegisterType((*BeerAddRequest)(nil), "pb.BeerAddRequest")
	proto.RegisterType((*BeerRemoveResponse)(nil), "pb.BeerRemoveResponse")
	proto.RegisterType((*BeerRemoveRequest)(nil), "pb.BeerRemoveRequest")
}

func init() { proto.RegisterFile("pkg/pb/beers.proto", fileDescriptor_75daee14f32918a9) }

var fileDescriptor_75daee14f32918a9 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x18, 0x84, 0x6b, 0xa7, 0x75, 0xc5, 0x3f, 0x84, 0xf2, 0x23, 0x20, 0x74, 0x8a, 0x0c, 0x43, 0xc4,
	0x90, 0xa2, 0x32, 0x31, 0xa6, 0x62, 0x43, 0x08, 0xc9, 0x3c, 0x00, 0xaa, 0xe5, 0x5f, 0x51, 0x85,
	0xd2, 0x18, 0xdb, 0xe1, 0xf9, 0x51, 0x12, 0x5a, 0x48, 0x1e, 0x80, 0xcd, 0x3a, 0xdf, 0xf9, 0xbb,
	0x93, 0x01, 0xed, 0x47, 0xb9, 0xb2, 0x7a, 0xa5, 0x89, 0x9c, 0xcf, 0xad, 0xab, 0x43, 0x8d, 0xdc,
	0x6a, 0xe9, 0xe0, 0x74, 0x43, 0xe4, 0x0a, 0x63, 0x14, 0x79, 0x5b, 0xef, 0x3d, 0x61, 0x0c, 0x7c,
	0x67, 0x12, 0x96, 0xb2, 0x6c, 0xa6, 0xf8, 0xce, 0x20, 0xc2, 0x74, 0xbf, 0xad, 0x28, 0xe1, 0x29,
	0xcb, 0x4e, 0x54, 0x77, 0x46, 0x09, 0xc2, 0x87, 0x6d, 0x68, 0x7c, 0x12, 0xa5, 0x2c, 0x8b, 0xd7,
	0x90, 0x5b, 0x9d, 0xbf, 0x75, 0x8a, 0xfa, 0xb9, 0xc1, 0x2b, 0x98, 0x93, 0x73, 0xef, 0x95, 0x2f,
	0x93, 0x69, 0x17, 0x15, 0xe4, 0xdc, 0x8b, 0x2f, 0xe5, 0x2d, 0xc4, 0x47, 0xe6, 0x67, 0x43, 0x3e,
	0x1c, 0x11, 0xec, 0x17, 0x21, 0x1b, 0xc0, 0xd6, 0xa5, 0xa8, 0xaa, 0xbf, 0xe8, 0xff, 0xca, 0xdd,
	0xc0, 0xd9, 0x5f, 0x6c, 0xdf, 0x6f, 0x44, 0xbd, 0xbb, 0x06, 0xd1, 0xbf, 0x87, 0x02, 0xf8, 0xeb,
	0xf3, 0x62, 0x82, 0x73, 0x88, 0x36, 0xc5, 0xd3, 0x82, 0xad, 0x03, 0xcc, 0xda, 0xbc, 0xc7, 0x7b,
	0x88, 0x0a, 0x63, 0x10, 0x5b, 0xf8, 0x70, 0xee, 0xf2, 0x7c, 0xa0, 0xf5, 0xcb, 0xe4, 0x04, 0x1f,
	0x41, 0xf4, 0x58, 0xbc, 0x38, 0x18, 0x06, 0x35, 0x96, 0x97, 0x63, 0xf9, 0x10, 0xd5, 0xa2, 0xfb,
	0xd1, 0x87, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0xb6, 0xfa, 0x4b, 0xe7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BeersClient is the client API for Beers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeersClient interface {
	Add(ctx context.Context, in *BeerAddRequest, opts ...grpc.CallOption) (*BeerAddResponse, error)
	Remove(ctx context.Context, in *BeerRemoveRequest, opts ...grpc.CallOption) (*BeerRemoveResponse, error)
}

type beersClient struct {
	cc *grpc.ClientConn
}

func NewBeersClient(cc *grpc.ClientConn) BeersClient {
	return &beersClient{cc}
}

func (c *beersClient) Add(ctx context.Context, in *BeerAddRequest, opts ...grpc.CallOption) (*BeerAddResponse, error) {
	out := new(BeerAddResponse)
	err := c.cc.Invoke(ctx, "/pb.Beers/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beersClient) Remove(ctx context.Context, in *BeerRemoveRequest, opts ...grpc.CallOption) (*BeerRemoveResponse, error) {
	out := new(BeerRemoveResponse)
	err := c.cc.Invoke(ctx, "/pb.Beers/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeersServer is the server API for Beers service.
type BeersServer interface {
	Add(context.Context, *BeerAddRequest) (*BeerAddResponse, error)
	Remove(context.Context, *BeerRemoveRequest) (*BeerRemoveResponse, error)
}

// UnimplementedBeersServer can be embedded to have forward compatible implementations.
type UnimplementedBeersServer struct {
}

func (*UnimplementedBeersServer) Add(ctx context.Context, req *BeerAddRequest) (*BeerAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedBeersServer) Remove(ctx context.Context, req *BeerRemoveRequest) (*BeerRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterBeersServer(s *grpc.Server, srv BeersServer) {
	s.RegisterService(&_Beers_serviceDesc, srv)
}

func _Beers_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeerAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeersServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Beers/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeersServer).Add(ctx, req.(*BeerAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beers_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeerRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeersServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Beers/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeersServer).Remove(ctx, req.(*BeerRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Beers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Beers",
	HandlerType: (*BeersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Beers_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Beers_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/beers.proto",
}
